# Generated by Django 3.1.3 on 2020-11-09 22:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HttpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('DELETE', 'DELETE'), ('PUT', 'PUT')], default='GET', help_text='HTTP method for the request', max_length=10)),
                ('url', models.URLField(help_text='URL for the request')),
                ('content_type', models.CharField(choices=[('application/json', 'application/json')], default='application/json', max_length=255)),
                ('payload', models.TextField(blank=True, help_text='Request body. Must be compatible with content type', max_length=2048, null=True)),
                ('eta', models.DateTimeField(default=django.utils.timezone.now, help_text='When the request is expected to be run.')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('F', 'Failed'), ('C', 'Completed')], default='P', editable=False, help_text='Request status', max_length=1)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HttpResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status_code', models.IntegerField(editable=False, help_text='HTTP response status. Eg, 200 or 404')),
                ('response', models.CharField(editable=False, max_length=2048, null=True)),
                ('request', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='rest_manager.httprequest')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
