# Generated by Django 3.1.3 on 2020-11-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpresponse',
            name='status_code',
            field=models.IntegerField(blank=True, editable=False, help_text='HTTP response status. Eg, 200 or 404', null=True),
        ),
    ]
